// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINAL_INTERN.Models.Models;

public partial class CategoriesOfCar
{
    public int Id { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<CarInfo> CarInfos { get; set; } = new List<CarInfo>();
}