// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINAL_INTERN.Models.Models;

public partial class Order
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public string NameOfCustomer { get; set; }

    public DateTime? Dates { get; set; }

    public string Email { get; set; }

    public int? Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}