// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FINAL_INTERN.Models.Models;

public partial class OrderDetail
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int AccountId { get; set; }

    public int CarId { get; set; }

    public string NameOfCar { get; set; }

    public int? Price { get; set; }

    public double? Total { get; set; }

    public virtual Account Account { get; set; }

    public virtual CarInfo Car { get; set; }

    public virtual Order Order { get; set; }
}